
-- ITS OK 

CREATE TABLE GROUPE (
    ID_GROUPE int NOT NULL AUTO_INCREMENT,
    ID_GROUPE_PERE INT, 
    NOM_GROUPE varchar(255) NOT NULL,
    MIN int NOT NULL,
    MAX int NOT NULL,
    TYPE_GROUPE varchar(255) NOT NULL,
    PRIMARY KEY (ID_GROUPE)
);


-- ITS OK

CREATE TABLE ETUDIANT (
    ID_ETUDIANT int NOT NULL AUTO_INCREMENT,
    NOM varchar(255) NOT NULL,
    PRENOM varchar(255) NOT NULL,
    PRIMARY KEY (ID_ETUDIANT)
);


-- ITS OK

CREATE TABLE PROMO (
    ID int NOT NULL AUTO_INCREMENT,
    GROUPE_PERE int NOT NULL,
    SOUS_GROUPE int NOT NULL,
    ETUDIANT int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GROUPE_PERE) REFERENCES GROUPE(ID_GROUPE),
    FOREIGN KEY (SOUS_GROUPE) REFERENCES GROUPE(ID_GROUPE),
    FOREIGN KEY (ETUDIANT) REFERENCES ETUDIANT(ID_ETUDIANT)
);


-- ITS OK

CREATE TABLE CHANGEMENT (
    ID int NOT NULL AUTO_INCREMENT,
    ETUDIANT int NOT NULL, 
    ID1_GROUPE_DEPART int NOT NULL,
    ID2_GROUPE_ARRIVE int NOT NULL,
    STATUS INT NOT NULL,
    FOREIGN KEY(ETUDIANT) REFERENCES ETUDIANT(ID_ETUDIANT),
    FOREIGN KEY(ID1_GROUPE_DEPART) REFERENCES GROUPE(ID_GROUPE),
    FOREIGN KEY(ID2_GROUPE_ARRIVE) REFERENCES GROUPE(ID_GROUPE),
    PRIMARY KEY (ID)
);

